const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { getBrokerMethodMetadata } = require("../shared/tool-registry.cjs");

test("desktop broker wires known-folder and fixed health methods and clears helper state on stop", () => {
  const main = fs.readFileSync(path.join(__dirname, "..", "src", "main.cjs"), "utf8");
  const broker = fs.readFileSync(path.join(__dirname, "..", "src", "host", "broker-server.cjs"), "utf8");
  const runtimeHost = fs.readFileSync(path.join(__dirname, "..", "src", "host", "runtime-host.cjs"), "utf8");
  assert.match(main, /createHostBrokerServer/);
  assert.match(broker, /createKnownFolderAccess/);
  assert.match(broker, /createLoopbackHealthProbe/);
  assert.equal(getBrokerMethodMetadata("local_list_known_folder").implementationKey, "known-folder.list");
  assert.equal(getBrokerMethodMetadata("local_read_known_folder").implementationKey, "known-folder.read");
  assert.equal(getBrokerMethodMetadata("local_probe_health").implementationKey, "health.probe");
  assert.equal(getBrokerMethodMetadata("local_request_host_access").implementationKey, "access.host.request");
  assert.match(broker, /createHostCapabilityStore/);
  assert.match(broker, /transactionRegistryPath:\s*path\.join\(app\.getPath\("userData"\),\s*"local-file-transactions\.json"\)/);
  assert.match(broker, /issueCapability/);
  assert.match(broker, /capabilityStore\?\.clear\(\)/);
  assert.match(runtimeHost, /createBrokerBootstrap/);
  assert.match(broker, /createBrokerChallenge/);
  assert.match(broker, /verifyBrokerProof/);
  assert.match(runtimeHost, /LPC_LOCAL_BROKER_PROTOCOL/);
  assert.match(runtimeHost, /LPC_LOCAL_BROKER_SESSION/);
  assert.match(runtimeHost, /LPC_LOCAL_BROKER_SECRET/);
  assert.match(broker, /knownFolderAccess\s*=\s*undefined/);
  assert.match(broker, /healthProbe\s*=\s*undefined/);
});
